server:
  port: 9091

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9090/oauth2/introspect
          client-id: client1
          client-secret: tempsecret1

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:~/dev
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop